// All reusable variables here
#let myLang = "en"
#let myName = "Lorenzo Soligo"
#let myMatricola = "2101057"
#let myTitle = "Explainable Machine Learning through Large Language Models: Analysis and Prompt Design"
#let myDegree = "Bachelor's Thesis"
#let myUni = "University of Padova"
#let myDepartment = "Department of Mathematics ''Tullio Levi-Civita''"
#let myFaculty = "Bachelor's Degree in Computer Science"
#let profTitle = "Prof. "
#let myProf = "Michele Scquizzato"
#let myCompany = "Zucchetti S.p.A."
#let myTutor = "Diego Polesel"
#let myLocation = "Padova"
#let myAA = "2025-2026"
#let myTime = "June 2026"