// All reusable variables here
#let myLang = "it"
#let myName = "Lorenzo Soligo"
#let myMatricola = "42"
#let myTitle = "Titolo della tesi"
#let myDegree = "Tesi di Laurea"
#let myUni = "Università di Padova"
#let myDepartment = "Dipartimento di Matematica ''Tullio Levi-Civita''"
#let myFaculty = "Corso di Laurea in Informatica"
#let profTitle = "Prof. "
#let myProf = "Michele Scquizzato"
#let myCompany = "Zucchetti S.p.A."
#let myTutor = "Diego Polesel"
#let myLocation = "Padova"
#let myAA = "2025-2026"
#let myTime = "Mese AAAA"